# Generated by Django 3.1.3 on 2020-12-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='default_article.jpg', upload_to='article_pictures'),
        ),
    ]
