# Generated by Django 3.1.3 on 2020-11-30 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('RRSP', 'Registered Retirement Savings Plan'), ('TFSA', 'Tax-Free Saving Account'), ('RESP', 'Registered Education Savings Plan'), ('MARGIN', 'Non-Registered Margin Account')], max_length=100)),
                ('brokerage', models.CharField(max_length=100)),
                ('cash_balance', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker_symbol', models.CharField(max_length=15)),
                ('num_shares', models.FloatField(default=1.0)),
                ('security_type', models.CharField(choices=[('CASH', 'Cash'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('OPTION', 'Option'), ('MUTUAL FUND', 'Mutual Fund')], max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('purchase_price', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_viewer.account')),
            ],
        ),
    ]
