# Generated by Django 3.1.3 on 2020-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='brokerage',
            field=models.CharField(choices=[('QTRADE', 'Qtrade Investor'), ('QUESTRADE', 'Questrade'), ('TD', 'TD Direct Investing'), ('NATIONAL BANK', 'National Bank Direct Brokerage'), ('SCOTIABANK', 'Scotia iTrade'), ('CIBC', "CIBC Investor's Edge"), ('INTERACTIVE', 'Interactive Brokers'), ('WEALTHSIMPLE', 'WealthSimple')], max_length=100),
        ),
    ]
